### ISSUE TITLE
Consolidate Webhook Configuration under notifiers Section for Improved DX

### ISSUE THREAD

**Issue by heryTz** [heryTz/backupman#26]
Currently, webhook configuration exists as a top-level section in the `config.yaml`. However, as discussed, webhooks serve the purpose of notifying external systems about Backupman events, similar to how email is used for notifications.

To enhance Developer Experience (DX), improve logical cohesion, and streamline the configuration, this issue proposes moving the webhooks configuration entirely under the notifiers section. This change directly aligns with Backupman's **Real-time Monitoring: Email, Webhook notifications** feature.

**Proposed Structure (Excerpt):**

```yaml
notifiers:
  mail:
    enabled: true
    # ... mail specific settings ...
  webhooks: # <--- New location for webhooks
    enabled: true
    endpoints:
      - name: My Webhook
        url: http://localhost:8080/webhook
        token: xxx
```

**Benefits of this change:**

- _Logical Cohesion:_ Groups all notification-related settings in one place, making the configuration easier to understand at a glance.

- _Improved DX:_ Developers looking for how to set up alerts or external communications will find all options consolidated under a single, intuitive notifiers section.

- _Consistency:_ Aligns the configuration file structure with the conceptual role of webhooks as a notification mechanism, as described in Backupman's features.

- _Future-Proofing:_ Provides a clear pattern for adding other notification types (e.g., SMS, push notifications) under a unified notifiers umbrella.
